### ISSUE TITLE
Issues with code  stuck

### ISSUE THREAD

**Issue by giepher** [luvit/luvit#1092] opened 2020-01-01 10:01 UTC
There's the test code
```
local Emitter = require('core').Emitter
local i= 0
local Client = Emitter:extend()
function Client:initialize()
  self:on('Method1', function ()
            print('Method1 -- '..i)
            i = i + 1
  end)
end
function Client:start()
while true do
  self:emit('Method1')
end -- END while
end
local x = Client:new()
x:start()
```

and output stucked like this:

```
Method1 -- 0
Method1 -- 1
Method1 -- 2
Method1 -- 3
...
Method1 -- 954
Method1 -- 955
Method1 -- 956
Metho
```
It's stuck the last line.  I test this because my server been stucked when I want print some log .

Is someone can  help?

**Comment by SinisterRectus** [comment] 2020-01-01 16:13
I'm not able to reproduce this. What platform and luvit version are you running?

**Comment by giepher** [comment] 2020-01-02 02:20
both mac and centos7 with  luvit 2.16,  At last it will display out of memory if I didn't kill the process.

**Comment by giepher** [comment] 2020-01-02 02:20
> I'm not able to reproduce this. What platform and luvit version are you running?

both mac and centos7 with luvit 2.16, At last it will display out of memory if I didn't kill the process.

**Comment by squeek502** [comment] 2020-01-02 02:36
You're getting out of memory errors with the exact code you posted?

**Comment by giepher** [comment] 2020-01-02 06:32
Method1 -- 118
Method1 -- 119
Method1 -- 120
Method1 -- 121
Method1 -- 122
Method1 -- not enough memory

**Comment by giepher** [comment] 2020-01-02 06:35
> You're getting out of memory errors with the exact code you posted?

Method1 -- 118
Method1 -- 119
Method1 -- 120
Method1 -- 121
Method1 -- 122
Method1 -- not enough memory
the "not enough memory"  shows after 1 or 2 minutes, the process memory increaced to 2G  my RAM is 16G.
it's ok when i comment the print

**Comment by squeek502** [comment] 2020-01-02 07:43
The version of LuaJIT that Luvit uses has a hard memory limit of 2GB so that part makes sense (see https://github.com/luvit/luvi/issues/211).

The lines not being printed might be something to do with your terminal and how it buffers output? Not sure. I can reproduce the out-of-memory error by running the code for quite a while, and it prints the whole time. Here's the number I get to:
```
Method1 -- 3449784
Method1 -- 3449785
not enough memory
```

Not sure why the memory is not being cleaned up, though. That might be a bug.

**Comment by SinisterRectus** [comment] 2020-01-03 15:45
A simplified example also increases memory consumption.
```lua
while true do
  collectgarbage()
  collectgarbage()
  print(collectgarbage('count'))
end
```
The same does not happen using `io.write`, so there must be a leak in luvit's custom `print`.

**Comment by SinisterRectus** [comment] 2020-01-03 15:50
Looks like it might be in `uv.write`. This also reproduces the leak.
```lua
local uv = require('uv')

local stdout
if uv.guess_handle(1) == 'tty' then
  stdout = assert(uv.new_tty(1, false))
else
  stdout = uv.new_pipe(false)
  uv.pipe_open(stdout, 1)
end

while true do
  collectgarbage()
  collectgarbage()
  stdout:write(collectgarbage('count'))
  stdout:write('\n')
end
```

**Comment by zhaozg** [comment] 2020-01-04 05:38
this should be move to https://github.com/luvit/luv

**Comment by zhaozg** [comment] 2020-01-04 10:45
Please try this
```
local uv = require('uv')

local stdout
if uv.guess_handle(1) == 'tty' then
  stdout = assert(uv.new_tty(1, false))
else
  stdout = uv.new_pipe(false)
  uv.pipe_open(stdout, 1)
end

while true do
  collectgarbage()
  collectgarbage()
  stdout:try_write(collectgarbage('count'))
  stdout:try_write('\n')
end
```

**Comment by SinisterRectus** [comment] 2020-01-06 00:28
I see no leak with that example. Should I open an issue in luvit/luv?

**Comment by squeek502** [comment] 2020-01-17 06:56
I think I figured out a bit about what's happening. With the following code:

```lua
local stdout
if uv.guess_handle(1) == 'tty' then
  stdout = assert(uv.new_tty(1, false))
else
  stdout = uv.new_pipe(false)
  uv.pipe_open(stdout, 1)
end

for i=1,10 do
  collectgarbage()
  collectgarbage()
  stdout:write(i .. ': ' .. collectgarbage('count') .. '\n', function() print('written ' .. i .. ': ' .. collectgarbage('count')) end)
end

uv.run()

collectgarbage()
collectgarbage()
print('after uv.run(): ' .. collectgarbage('count'))
```

I get the output:

```
1: 96.4072265625
2: 96.7607421875
3: 97.1845703125
4: 97.5380859375
5: 97.8916015625
6: 98.3076171875
7: 98.6611328125
8: 99.1396484375
9: 99.4931640625
10: 99.8466796875
written 1: 100.310546875
written 2: 100.4052734375
written 3: 100.5009765625
written 4: 100.5966796875
written 5: 100.6923828125
written 6: 100.7880859375
written 7: 100.8837890625
written 8: 100.9794921875
written 9: 101.0751953125
written 10: 101.1708984375
after uv.run(): 96.6650390625
```

meaning that none of the callbacks get called until the entire loop is finished. In the code [in this comment](https://github.com/luvit/luvit/issues/1092#issuecomment-570611187), this doesn't happen until loop GC during lua_close since `uv.run()` is never called. 

In my code, uv.run() is called which then calls the write callbacks and then allows all those write reqs (and their associated strings) to be freed. `try_write` doesn't have this problem because it doesn't need to keep the strings around at all.

Not totally sure if this is a flaw in Luv or if it's expected behavior here. Seems like it might be expected behavior? It's kind of weird though.

**Comment by zhaozg** [comment] 2020-01-17 07:23
> In my code, uv.run() is called which then calls the write callbacks and then allows all those write reqs (and their associated strings) to be freed. try_write doesn't have this problem because it doesn't need to keep the strings around at all.

Only on tty, in libuv examples, the use try_write to output on tty device.

**Comment by squeek502** [comment] 2020-01-17 07:32
Maybe Luvit's `print` wrapper should use `try_write` instead of `write` then?

https://github.com/luvit/luvit/blob/d841d165bdf60d8acd582724c0af50861f90dd1d/deps/pretty-print.lua#L300-L320

**Comment by SinisterRectus** [comment] 2020-01-17 16:21
From http://docs.libuv.org/en/v1.x/stream.html#c.uv_write
> The memory pointed to by the buffers must remain valid until the callback gets called. This also holds for uv_write2().

----

From http://docs.libuv.org/en/v1.x/stream.html#c.uv_try_write
> Same as uv_write(), but won’t queue a write request if it can’t be completed immediately.

What implication does this have for `print` behavior? Is there a chance that data would not be printed? Would we have to maintain a queue?

**Comment by squeek502** [comment] 2020-01-17 18:57
> What implication does this have for `print` behavior? Is there a chance that data would not be printed?

Probably. See things like https://github.com/luvit/luvit/pull/1007 / https://github.com/luvit/lit/issues/222.

**Comment by SinisterRectus** [comment] 2020-01-17 21:13
Looks like it's not a unique issue.

nodejs/node#3524
nodejs/node#23729

I think it's okay to leave it as is.

**Comment by squeek502** [comment] 2020-01-17 21:15
Agreed, closing.

**Closed by squeek502** 2020-01-17 21:15 UTC
Labels: bug
