### ISSUE TITLE
Cannot arbitrarily read data from a stream

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luvit#940] opened 2016-12-12 20:26 UTC
The following does not work as expected.

```lua
local fs = require('fs')
local stream = require('stream')

local file = io.open('test.txt', 'w')
file:write('abcdef')
file:close()

file = fs.createReadStream('test.txt')
p(file:read(6)) -- nil

file = fs.createReadStream('test.txt')
local sink = stream.Writable:new()
function sink:write(chunk) p(chunk) end
file:pipe(sink) -- 'abcdef'
```

When I attempt to read the stream directly, I get `nil`. Piping the stream to a different one works, though. I've tried all combination of `pause`, `resume` and `on:('readable', ...)` that I can think of, but can't seem to read from streams with anything other than `on:('data', ...)` . Am I doing something wrong?

**Comment by creationix** [comment] 2016-12-13 18:37
The luvit `fs` module is callback based and doesn't typically return values in the default non-blocking APIs.  You probably need to provide a callback function to get the result.

**Comment by creationix** [comment] 2016-12-13 18:38
That said, I think this particular API is a clone of node's streams 2 where read is in fact sync, but only after a "readable" event.

https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_readable_read_size

**Comment by SinisterRectus** [comment] 2016-12-13 19:16
I did try the event, but it still returns `nil`.

```lua
local fs = require('fs')
file = fs.createReadStream('test.txt')

file:on('readable', function()
	print(file:read(6)) -- nil
end)

file:resume() -- doesn't work without resume
```
The equivalent Node code does work:
```js
var fs = require('fs');
var file = fs.createReadStream('test.txt');

file.on('readable', function() {
	var chunk = file.read(6)
	if (chunk !== null)
		console.log(chunk.toString()); // 'abcdef'
});
```
In my application, I'm not actually reading from a file, I'm spawning a process and reading from `child.stdout`. I did manage to get my own thing working using `uv.spawn` directly, but I'd like to see if the Luvit API is working as intended.

**Comment by creationix** [comment] 2016-12-13 20:49
This is the library I use personally https://github.com/luvit/lit/blob/master/deps/coro-spawn.lua

I guess this is a bug in luvit's stream library somewhere.

**Comment by SinisterRectus** [comment] 2016-12-13 21:52
That's a nice library. I might make use of it, but it doesn't seem to allow for reading a specific number of bytes from the stream, which is ultimately what I'm seeking. To compensate, I just collect data from `stdout:read_start` when necessary and deliver appropriately sized chunks to a consumer, pretty much what I expected `Stream:read(n)` to do internally.

**Comment by creationix** [comment] 2016-12-15 17:31
yeah, it doesn't support specified bytes, but a layer that does that could be added on top pretty easily.

Sorry for the trouble.

**Comment by SinisterRectus** [comment] 2016-12-15 21:00
Yeah, it was easy. [Makes my code neater, too](https://github.com/SinisterRectus/Discordia/commit/caf01e5739702cfc5c2f297b6a9e979dabd08e4c#diff-c0022e1b64bf43a7324b65f3ae518793L37). Thanks for the tip. We can leave this open if there is a bug in the Luvit module.

**Comment by creationix** [comment] 2016-12-15 21:01
Yes, the stream module does seem broken.  I just don't know if/when it will be fixed.  Let's leave this open for now.

**Comment by Miigon** [comment] 2016-12-31 12:06
Hey guys!I found that when it's the first time `read()`was called,it always return `nil`(no matter if it's readable)

**Comment by Miigon** [comment] 2016-12-31 16:55
I think I found the bug:
`stream` operations are sync,while `fs` operations are async.
When the first time to call `file:read()`,`fs.ReadStream:_read()` is called to read data from file.
```lua
-- codes at [deps/fs.lua:662]
-- in function `fs.ReadStream:_read(n)`
  fs.read(self.fd, to_read, self.offset, function(err, bytes)
    p ("fs.read",bytes)
    if err then return self:destroy(err) end
    if #bytes > 0 then
      self.bytesRead = self.bytesRead + #bytes
      if self.offset then
        self.offset = self.offset + #bytes
      end
      self:push(bytes)
    else
      self:push()
    end
  end)
```
So the problem is: `fs.read` is an async function,that means the callback may not be called before `_read()` returns.That's the reason `file:read()` returning nil at the first time.After callback is called,`file:read()` no longer need to call `_read()` to read from file.It just return data from buffer.So at the second time, `file:read()` works correctly.

**Comment by creationix** [comment] 2017-01-03 19:08
Awesome work @Miigon

**Closed** 2017-01-03 19:07 UTC

**Comment by joerg-krause** [comment] 2017-02-24 08:18
Unfortunately, this breaks reading from `/dev/input/event0` for me. The following snippet is working before that commit, but not afterwards as `onRead()` is never called.

``` Lua
local fs = require("fs")
local Emitter = require("core").Emitter
local KeyEventListener = Emitter:extend() -- class table

function KeyEventListener:initialize(id)
  self.id = id
  self:wrap("onOpen")
  self:wrap("onRead")
  fs.open("/dev/input/event" .. id, "r", "0644", self.onOpen)
end

function KeyEventListener:onOpen(fd)
  self.fd = fd
  self:startRead()
end

function KeyEventListener:startRead()
  fs.read(self.fd, ffi.sizeof("struct input_event"), nil, self.onRead)
end

function KeyEventListener:onRead(data)
  p(data)
  if self.fd then self:startRead() end
end

function KeyEventListener:close(callback)
  local fd = self.fd
  self.fd = nil
  fs.close(fd, callback)
end

return {
  KeyEventListener = KeyEventListener
}
```

**Comment by Miigon** [comment] 2017-04-04 09:28
So sorry. @SinisterRectus 
Stream apis isn't always synchronous.
So after this:
```
file = fs.createReadStream('test.txt')
p(file:read(6)) -- nil
```
`nil`means the stream is reading data asynchronously.
You should add a 'data' Listener to handle the data.

**Comment by Miigon** [comment] 2017-04-04 09:30
@creationix Is there a way to make stream operations sync?

**Comment by creationix** [comment] 2017-04-05 03:18
So this stream interface is modeled after node's stream interface. https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_readable_streams

Full disclaimer, I don't like this interface and never use it in luvit.  I feel it's over complicated and we can do much better taking coroutines into account.

That said, there is a fundamental tradeoff in node-style APIs.  You code can *either* be non-blocking/fast or it can be blocking and destroy your concurrency.  The non-blocking APIs cannot return a value if it's not there.  For example, trying to read from a stream when the read buffer is empty will either block the entire process (this is the readSync style) till data is there, or it will return nill and notify you of the data later through some other means.  Using sync APIs are dangerous in server situations since you may have other concurrent requests that you wanted to handle, but a single sync call will block the whole world.

Again, this tradeoff comes from node.  In lua we have native coroutines and there is a third option that I personally always take in my luvit code.  I create a coroutine as a light-weight green-thread/process type thing (like handing a single http request in a web server).  Then in this coroutine, I use APIs that block when data isn't ready yet, but only block the coroutine, not the entire process.  Other coroutines can happily run while the coroutine waiting for more data is blocked.  Code can be written in the simpler sync style with return values instead of callbacks and events.

So "Is there a way to make stream operations sync?"  That depends on what you mean.  If you mean within the context of the luvit/stream module which is a clone of the nodeJS APIs, then no.  It needs to copy whatever node did.  If you mean generally in luvit, then yes, use my coroutine based APIs instead.
